### PR TITLE
feat export image

### PR DESCRIPTION
**Pull request by GideonSenku**
- feat: add export image
- fix: double click error

### CODE REVIEW

**Comment by GideonSenku** [comment]
looks like

image

**Comment by Justineo** [comment]
Thank you! Can you provide a screenshot and what is the difference between the added feature and Figma’s built-in export feature?

**Comment by GideonSenku** [comment]
> Thank you! ~Can you provide a screenshot and~ _missed that on my phone_
> 
> What is the difference between the added feature and Figma’s built-in export feature?

This PR doesn't differ much from Figma; it simply makes operations more convenient and more similar to DevMode. The actual goal is to add a button for uploading to the CDN in the future.

**Comment by Justineo** [comment]
The main purpose of this extension is not to compete with Dev Mode and I do not intend to include features already accessible in view-only mode in Figma. Uploading to CDN sounds useful but it will introduce quite a lot complexity into this extension (for both implementation and user preferences).

**Comment by GideonSenku** [comment]
> The main purpose of this extension is not to compete with Dev Mode and I do not intend to include features already accessible in view-only mode in Figma. Uploading to CDN sounds useful but it will introduce quite a lot complexity into this extension (for both implementation and user preferences).

I get it, but there have other problem, u didn't `preventDefault` double click with the IconButton

**Comment by Justineo** [comment]
> I get it, but there have other problem, u didn't `preventDefault` double click with the IconButton

Yes that's a good catch. Would you mind split the PR and make a separate fix for this?

**Comment by Justineo** [comment]
PS. I think in such case it's better to not stop double click from the button. Instead we should ensure when we listen to click or double click events on a container element which might contain other clickable elements, the event target isn't coming from some interactive (eg. not from inside a focusable element (inputs, buttons, elements with tabindex or contenteditable, etc.)).

**Comment by Justineo** [comment]
I'm gonna close this for now as we do have access to similar features already in Figma itself.

**Pull request closed without merging**
